# Generated by Django 4.2.2 on 2023-06-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("Id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("description", models.CharField(max_length=4000)),
                ("address", models.CharField(max_length=500)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
