# Generated by Django 4.2.2 on 2023-06-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_id_alter_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="Id",
            field=models.UUIDField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
