# Generated by Django 4.2.2 on 2023-06-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="Id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
